# 服务器端口
server:
  port: 80

spring:
  profiles:
    active: dev
#spring.mvc.static-path-pattern=/static/**

  #redis jedis配置
  #redis:
    # Redis数据库索引（默认为0）
  #  database: 0
    # Redis服务器地址
  #  host: 127.0.0.1
    # Redis 端口
  #  port: 6379
    # Redis 服务器连接密码（默认为空）
    #password:
 #   pool:
      # 连接池最大连接数（使用负值表示没有限制）
 #     max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
 #     max-wait: -1
      # 连接池中的最大空闲连接
 #     max-idle: 8
      # 连接池中的最小空闲连接
 #     min-idle: 0
      # 连接超时时间（毫秒）
 #   timeout: 0


# mybatis
mybatis:
  # XxxMapper.xml 配置文件路径
  mapper-locations: classpath:/com/jiang/chatroom/dao/*Mapper.xml
  # mybatis 配置文件全局配置文件路径
  config-location: classpath:/mybatis/mybatis-config.xml


