# 服务器端口
server:
  port: 80

#spring.mvc.static-path-pattern=/static/**

# 数据库连接
spring:
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatroom?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: jiangBUG

  # 静态资源
  resources:
    # 静态资源查找路径
    static-locations: classpath:/static
    # 开发环境关闭缓存
    chain:
      cache: false

  # thymeleaf模板引擎
  thymeleaf:
    prefix: classpath:/static/html/
    suffix: .html
    cache: false

  #redis jedis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis 端口
    port: 6379
    # Redis 服务器连接密码（默认为空）
    #password:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
    timeout: 0


  #spring-session 使用
  session:
    store-type: none


# mybatis
mybatis:
  # XxxMapper.xml 配置文件路径
  mapper-locations: classpath:/com/jiang/chatroom/dao/*Mapper.xml
  # mybatis 配置文件全局配置文件路径
  config-location: classpath:/mybatis/mybatis-config.xml


