# \u670D\u52A1\u5668\u7AEF\u53E3
server:
  port: 80

#spring.mvc.static-path-pattern=/static/**

# \u6570\u636E\u5E93\u8FDE\u63A5
spring:
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatroom?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root

  # \u9759\u6001\u8D44\u6E90
  resources:
    # \u9759\u6001\u8D44\u6E90\u67E5\u627E\u8DEF\u5F84
    static-locations: classpath:/static/,classpath:/static/templates,classpath:/static/js,classpath:/static/css
    # \u5F00\u53D1\u73AF\u5883\u5173\u95ED\u7F13\u5B58
    chain:
      cache: false

  # thymeleaf\u6A21\u677F\u5F15\u64CE
  thymeleaf:
    prefix: classpath:/static/html/
    suffix: .html

  #redis jedis\u914D\u7F6E
  redis:
    # Redis\u6570\u636E\u5E93\u7D22\u5F15\uFF08\u9ED8\u8BA4\u4E3A0\uFF09
    database: 0
    # Redis\u670D\u52A1\u5668\u5730\u5740
    host: 127.0.0.1
    # Redis\u670D\u52A1\u5668\u8FDE\u63A5\u7AEF\u53E3
    port: 6379
    # Redis\u670D\u52A1\u5668\u8FDE\u63A5\u5BC6\u7801\uFF08\u9ED8\u8BA4\u4E3A\u7A7A\uFF09
    #password:
    pool:
      # \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
      max-active: 200
      # \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
      max-wait: -1
      # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
      max-idle: 8
      # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
      min-idle: 0
      # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09
    timeout: 0


  #spring-session \u4F7F\u7528
  session:
    store-type: none


# mybatis
mybatis:
  # XxxMapper.xml\u914D\u7F6E\u6587\u4EF6\u8DEF\u5F84
  mapper-locations: classpath:/com/jiang/chatroom/dao/*Mapper.xml
  # mybatis \u914D\u7F6E\u6587\u4EF6\u5168\u5C40\u914D\u7F6E\u6587\u4EF6\u8DEF\u5F84
  config-location: classpath:/mybatis/mybatis-config.xml


